// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using MomVibe.Infrastructure.Persistence;

#nullable disable

namespace MomVibe.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260527000002_AddOffers")]
    partial class AddOffers
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder) { }
    }
}
