// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using MomVibe.Infrastructure.Persistence;

#nullable disable

namespace MomVibe.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260502000001_AddUserRatings")]
    partial class AddUserRatings
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Raw-SQL migration; model snapshot handled separately.
        }
    }
}
